### ISSUE TITLE
Paragraph in the right margin

### ISSUE THREAD

**Issue by lyonel2017** [acsl-language/acsl#52]
In the release 1.13 of ACSL manual, companion to Frama-C 17 - Chlorine, in section 2.4.4 "Statement contracts", at the end of page 45, a paragraph is placed in the right margin.

**Comment by pbaudin** [comment]
Thanks @lyonel2017. 
The text seems be to a margin note that has not been removed before the pdf export. The text has not to be considered, except for the author of the note. Perhaps, it would have been preferable for the author to open an new issue (labelled "clarification request") instead of introducing a such latex `\marginpar`...

**Comment by pbaudin** [comment]
Will be fixed by #54.
